// resources/js/svelte/Canvas/CanvasLines.svelte
<script lang="ts">
    import Line from "@/js/svelte/Elements/Line.svelte";
    import {lineIds} from "@/js/stores/linesStore";

    const linesKeys = $derived($lineIds);
</script>

<div class="relative top-0 left-0 select-none inset-0 w-0 h-0">
    {#each linesKeys as key (key)}
        {#if key}
            <Line id={key}/>
        {/if}
    {/each}
</div>

// resources/js/components/Canvas/CanvasLines.vue
<script lang="ts" setup>
import CanvasLine from "@/js/components/Canvas/CanvasLine.vue";
import {onMounted} from "vue";
import {v4 as uuidv4} from "uuid";
import {useStore} from "@/js/stores/store";

const store = useStore();

onMounted(() => {
    store.lines.push({
        id: uuidv4(),
        startId: uuidv4(),
        startX: 20,
        startY: 30,
        endId: uuidv4(),
        endX: 80,
        endY: 60,
    });
})
</script>

<template>
    <div id="canvas-lines"
         :style="store.canvasMatrixStyle"
         class="relative top-0 left-0 select-none inset-0 w-0 h-0">
        <CanvasLine v-for="line in store.lines" :key="line.id" :line="line"/>
    </div>
</template>
