// resources/js/svelte/Canvas/CanvasElement.svelte
<script lang="ts">
    import DebugDot from "@/js/svelte/Debug/DebugDot.svelte";
    import {DebugColor} from "@/js/components/Debug/DebugEnums";
    import {onMount} from 'svelte';
    import BaseElement from "@/js/svelte/Elements/BaseElement.svelte";
    import Port from "@/js/svelte/Elements/Ports/Port.svelte";
    import {ColorName, ElementTypeColor, PortType} from "@/js/stores/constants";

    let {element} = $props();
    let elementRef;
    let observer;
    let size = $state({width: 0, height: 0});

    onMount(() => {
        if (elementRef) {
            observer = new ResizeObserver((entries) => {
                for (const entry of entries) {
                    size = {
                        width: entry.contentRect.width,
                        height: entry.contentRect.height,
                    };
                }
            });
            observer.observe(elementRef);
        }
        return () => {
            if (observer) {
                observer.disconnect();
                observer = null;
            }
        };
    });
</script>

<div bind:this={elementRef}
     class="absolute left-0 top-0 border rounded-lg"
     style:transform={`matrix(1,0,0,1,${element.x},${element.y})`}
>
    <DebugDot size="1" color={DebugColor.Green}/>
    <BaseElement element={element}>
        {#snippet inputActionPorts()}
            {#each Object.values(element.ports).filter(port => port.type === PortType.ActionInput) as port}
                <Port port={port} baseColor={ColorName[ElementTypeColor[element.type]]}/>
            {/each}
        {/snippet}
        {#snippet outputActionPorts()}
            {#each Object.values(element.ports).filter(port => port.type === PortType.ActionOutput) as port}
                <Port port={port} baseColor={ColorName[ElementTypeColor[element.type]]}/>
            {/each}
        {/snippet}
        {#snippet inputDataPorts()}
            {#each Object.values(element.ports).filter(port => port.type === PortType.DataInput) as port}
                <Port port={port} baseColor={ColorName[ElementTypeColor[element.type]]}/>
            {/each}
        {/snippet}
        {#snippet outputDataPorts()}
            {#each Object.values(element.ports).filter(port => port.type === PortType.DataOutput) as port}
                <Port port={port} baseColor={ColorName[ElementTypeColor[element.type]]}/>
            {/each}
        {/snippet}
        <div>Content</div>
    </BaseElement>
</div>

// resources/js/components/Canvas/CanvasElement.vue
<script lang="ts" setup>
import {Element} from '@/js/interfaces'
import {useStore} from '@/js/stores/store';
import BaseElement from "@/js/components/Elements/BaseElement.vue";
import {ColorName, ElementTypeColor, PortType} from "@/js/stores/constants";
import Port from "@/js/components/Elements/Ports/Port.vue";

const store = useStore();

const props = defineProps<{ element: Element; }>();
</script>
<template>
    <BaseElement :element="props.element" :key="props.element.id">
        <template v-slot:inputActionPorts>
            <Port
                v-for="[key, port] in Object.entries(props.element.ports).filter( ([key, port]) => port.type === PortType.ActionInput )"
                :key="key"
                :port="port"
                :baseColor="ColorName[ElementTypeColor[props.element.type]]"/>
        </template>
        <template v-slot:outputActionPorts>
            <Port
                v-for="[key, port] in Object.entries(props.element.ports).filter( ([key, port]) => port.type === PortType.ActionOutput )"
                :key="key"
                :port="port"
                :baseColor="ColorName[ElementTypeColor[props.element.type]]"/>
        </template>
        <template v-slot:inputDataPorts>
            <Port
                v-for="[key, port] in Object.entries(props.element.ports).filter( ([key, port]) => port.type === PortType.DataInput )"
                :key="key"
                :port="port"
                :baseColor="ColorName[ElementTypeColor[props.element.type]]"/>
        </template>
        <template v-slot:outputDataPorts>
            <Port
                v-for="[key, port] in Object.entries(props.element.ports).filter( ([key, port]) => port.type === PortType.DataOutput )"
                :key="key"
                :port="port"
                :baseColor="ColorName[ElementTypeColor[props.element.type]]"/>
        </template>
        <div>Content</div>
    </BaseElement>
</template>
