// resources/js/svelte/App.svelte
<script lang="ts">
    import SideBar from "@/js/svelte/Panels/SideBar.svelte";
    import Canvas from "@/js/svelte/Canvas/Canvas.svelte";
</script>

<SideBar/>
<div class="sm:ml-64 h-screen  pt-16 border-0 box-border flex items-center justify-center relative">
    <div class="relative top-0 left-0 w-full h-full">
        <Canvas/>
    </div>
</div>

// resources/js/components/App.vue
<script setup>
    import SideBar from "./SideBar.vue";
    import Canvas from "./Canvas.vue";
    import CanvasTopPanel from "./CanvasTopPanel.vue";
</script>

<template>
    <SideBar />
    <div class="p-4 sm:ml-64 h-screen flex flex-col">
        <CanvasTopPanel class="w-full mt-14" />
        <Canvas class="grow w-full mt-4" />
    </div>
</template>
