// resources/js/components/Canvas/CanvasElements.vue
<script lang="ts" setup>
import {useStore} from "@/js/stores/store";
import CanvasElement from "@/js/components/Canvas/CanvasElement.vue";
import {DebugColor} from "@/js/components/Debug/DebugEnums";
import DebugDot from "@/js/components/Debug/DebugDot.vue";

const store = useStore();
</script>

<template>
    <div id="canvas" :style="store.canvasMatrixStyle" class="relative top-0 left-0 select-none inset-0 w-0 h-0">
        <DebugDot :show="true" :color="DebugColor.Red" :size="2"/>
        <CanvasElement v-for="element in store.elements" :key="element.id" :element="element"/>
    </div>
</template>

// resources/js/svelte/Canvas/CanvasElements.svelte
<script>
    import DebugDot from "@/js/svelte/Debug/DebugDot.svelte";
    import {store} from '@/js/svelte/Store/store';
    import CanvasElement from "@/js/svelte/Canvas/CanvasElement.svelte";
</script>

<div
    style:transform={`matrix(${$store.canvasMatrix.scale}, 0, 0, ${$store.canvasMatrix.scale}, ${$store.canvasMatrix.x}, ${$store.canvasMatrix.y})`}
    class="relative top-0 left-0 select-none inset-0 w-0 h-0">
    <DebugDot size="2"/>
    {#each Object.entries($store.elements) as [id, element]}
        <CanvasElement element={element}/>
    {/each}
</div>
